apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: snak-app-dragonfly
  namespace: default
  labels:
    app: dragonfly
spec:
  image: docker.dragonflydb.io/dragonfly:latest
  replicas: 1
